### ISSUE TITLE
Ordering of .cs3110 config compile.opam_packages is not preserved

### ISSUE THREAD

**Issue by jcao219** [cs3110/tools#129] opened 2015-11-18 05:45 UTC
Say you have

    compile.opam_packages=unix,anotherpackage

"unix" and "anotherpackage" should be passed to ocamlfind exactly in that order.  Otherwise, if anotherpackage requires unix, there would be no way to set up .cs3110 without causing error.

**Comment by remyjette** [comment] 2015-11-18 07:41
This is because `util/cli_config.ml` uses a `StringSet` data structure to store the packages...I think this was done to avoid needing to think about removing duplicates...not sure, it was written before I started working on these tools.

With that being said...could you provide an example sequence of packages that don't work?

The order ideally shouldn't matter if the packages are written properly - packages should define their own dependencies in a `myocamlbuild.ml` file, so that this doesn't matter.

For example, the `async_unix` package requires the `core` package, but you don't need to explicitly require them in any particular ordering - the dependencies should be resolved by the packages declaring them. As a result, not only does the ordering of `async_unix` and `core` not matter, `core` doesn't even need to be specified at all.

Of course, if you're running into a particular bug because of the ordering, I'd be happy to take a look...it'd just be easier to actually write a fix if I could reproduce it, so if you could provide a series of packages that are causing this issue I'll investigate further.

**Comment by jcao219** [comment] 2015-11-18 07:50
Ah yes,

I'm specifically running into this issue with packages `unix` and `irc-client.unix` (part of `irc-client`).

I want to be able to put this in my .cs3110 file:

    compile.opam_packages=unix,irc-client.unix

I wrote a fix that seems to work.  Without it, cs3110 passes those two in alphabetical order, which causes irc-client.unix to fail.

**Comment by remyjette** [comment] 2015-11-18 08:30
The example code in the README of that repo works fine - I put it in a file `irc.ml`, then compiled with

```
cs3110 compile -p irc-client.lwt -thread irc.ml
```

Just as a test, I also made a file that did nothing but `open Irc_client_unix.Client` and ran

```
cs3110 compile -p irc-client.unix,unix test.ml
```

(The added dependency on the `unix` package wasn't needed above, I just added it to make sure it wasn't messing with anything).

I'm curious what's causing yours to break - all I did was `opam install irc-client` to install it then compiled the above.

**Comment by jcao219** [comment] 2015-11-18 08:31
I also realized this. 

I reduced my program to a minimal test.ml:

    module C = Irc_client_unix

Then I compiled with:  

    cs3110 compile -p irc-client.unix,unix test

**Comment by remyjette** [comment] 2015-11-18 22:18
Ah I see now. Thanks for that minimal case, and for the pull request. I'll take a look at your PR soon.

In the meantime, in your README with instructions to the grader for your project, you should either tell them the full -p flag to pass to cs3110 compile (if the PR isn't accepted yet) or tell them to update 3110-tools (if it is).

**Closed** 2015-12-07 21:56 UTC
